# HostAtHome - Minecraft Server Configuration
# Maps directly to itzg/minecraft-server environment variables
# https://docker-minecraft-server.readthedocs.io/en/latest/variables/

environment:
  version:
    key: VERSION
    value: LATEST
  memory:
    key: MEMORY
    value: 2G
  eula:
    key: EULA
    value: "TRUE"

server:
  motd:
    key: MOTD
    value: "HostAtHome Minecraft Server"
  max-players:
    key: MAX_PLAYERS
    value: 20
  gamemode:
    key: GAMEMODE
    value: survival
  difficulty:
    key: DIFFICULTY
    value: normal
  hardcore:
    key: HARDCORE
    value: "FALSE"
  pvp:
    key: PVP
    value: "TRUE"

world:
  level-type:
    key: LEVEL_TYPE
    value: default
  seed:
    key: SEED
    value: ""
  spawn-protection:
    key: SPAWN_PROTECTION
    value: 16
  view-distance:
    key: VIEW_DISTANCE
    value: 10

network:
  online-mode:
    key: ONLINE_MODE
    value: "TRUE"
  white-list:
    key: WHITE_LIST
    value: "FALSE"
